# Generated by Django 2.1.5 on 2019-03-08 13:38

from django.conf import settings
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
                ('body', froala_editor.fields.FroalaField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('likes', models.ManyToManyField(blank=True, related_name='code_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
