# Generated by Django 2.1.5 on 2019-03-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code', '0002_auto_20190308_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='html',
            name='likes',
        ),
        migrations.DeleteModel(
            name='HTML',
        ),
    ]
